# systemd-tmpfiles: Regole dichiarative per la persistenza di Ermete OS su bare-metal
# Tipo  Percorso                  Modalità Utente Gruppo Età Argomento
# 1. Ricreazione sicura della Home Directory e copia dello scheletro (.bashrc, etc)
d       /var/home/ermete          0700     ermete ermete -   -
C       /var/home/ermete          -        -      -      -   /etc/skel
