#!/usr/sbin/nft -f
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        
        # 1. Ottimizzazione Conntrack via vmap per performance O(1)
        ct state vmap { established : accept, related : accept, invalid : drop }
        
        # 2. Loopback nativo
        iifname "lo" accept
        
        # 3. Servizi Core di Rete (DHCP & mDNS)
        udp dport 68 accept
        udp dport 5353 accept
        
        # 4. Gestione ICMP e ICMPv6
        ip protocol icmp icmp type { echo-request, destination-unreachable, router-advertisement, time-exceeded, parameter-problem } accept
        ip6 nexthdr icmpv6 icmpv6 type { echo-request, destination-unreachable, packet-too-big, time-exceeded, parameter-problem, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept

        # 5. Accesso Amministrativo
        tcp dport 22 accept
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
    }
    chain output {
        type filter hook output priority 0; policy accept;
    }
}
