[UKI]
SecureBootSigningTool=systemd-sbsign
SignKernel=false
# Abilitare in produzione fornendo i certificati PEM corretti per sbsign:
# SecureBootPrivateKey=/etc/kernel/secure-boot-private-key.pem
# SecureBootCertificate=/etc/kernel/secure-boot-certificate.pem